### ISSUE TITLE
Support additional languages

### ISSUE THREAD

**Issue by thisandagain** [thisandagain/sentiment#104]
From PR #93:

We'll need to establish a set of labeled sentences (see #103 as well as the original AFINN paper) in order be able to determine the accuracy of each translation. While Google Translate is great, sentiment can be pretty subtle and so I wonder if something like Pootle or Transifex might be able to help us source translations of the AFINN word list with greater confidence.

I've been thinking about ways to fund a CrowdFlower campaign to handle establishing labeled corpora for different languages. I don't think it would take much (maybe $60 - $120 USD) per language to get things started.

/cc @dkocich

**Comment by EmilStenstrom** [comment]
Here's a fork with a translated version of AFINN: https://github.com/AlexGustafsson/sentiment-swedish

**Comment by kubawolanin** [comment]
And here's a fork with a Polish version of AFINN: https://github.com/kubawolanin/sentiment-polish 😉 
Thank you for your amazing work!

**Comment by thisandagain** [comment]
Amazing! Thanks for sharing @EmilStenstrom and @kubawolanin. 😄

**Comment by Ekliptor** [comment]
What exactly needs to be changed to add a language?
I'm thinking about adding German.

If it's just a matter of translating the build/AFINN.json file: Wouldn't it be better to keep it all in one project instead of forking it? And then adding an API call so the user can set the language when loading the library.

**Comment by thisandagain** [comment]
@Ekliptor Good question. I think in order for me to feel good about adding an additional language I think we would need the translated `build/AFINN.json` file plus a labeled corpora (such as the labeled dataset we have of [Amazon, IMDB, and Yelp reviews from UCI](https://archive.ics.uci.edu/ml/datasets/Sentiment+Labelled+Sentences)) that permit us to evaluate the accuracy of those translations.
