### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by thisandagain** [thisandagain/sentiment#112]
Related to #111 #107 

- [ ] Briefly describe the approach taken by AFINN
- [ ] Briefly describe the how the tokenizer works
- [ ] Briefly describe each property of the returned object

**Comment by therishabhpandey** [comment]
Should this be added to README or use separate file?

**Comment by thisandagain** [comment]
Good question! I think adding to the README should still be ok for now. If things get too long I think my inclination would be to move some of the detailed documentation into a Github wiki.

**Comment by therishabhpandey** [comment]
Ok. I'll use your comment on #107

**Comment by therishabhpandey** [comment]
Check it out, #124. Looks alright.
