### ISSUE TITLE
Some negative words can be used to emphasize the meaning of another word.

### ISSUE THREAD

**Issue by lukechilds** [thisandagain/sentiment#117]
e.g:

```js
sentiment('this is good'); // score: 3
sentiment('this is crazy good'); // score: 1
sentiment('this is fucking good'); // score: -1
```

I don't think this is a duplicate of "Support for double negatives" (#109) as it's not really a "double negative", it just contains a word that could in some contexts be negative but in other contexts be used to emphasize the meaning of another word.

Ideally sentiment would understand that in the string `this is fucking good` the word `fucking` is emphasizing the word `good`.

So `fucking good` would have a score of `good` multiplied by the intensity of `fucking`.

So if `good` has a score of 3, `crazy` has an intensity of 1.2 and `fucking` has an intensity of 2. You'd get:

```js
sentiment('this is good'); // score: 3
sentiment('this is crazy good'); // score: 3.6
sentiment('this is fucking good'); // score: 6
```

I don't really have a clue what I'm talking about so maybe this is way outside of the scope of this module. It would be great if this worked though.

**Comment by thisandagain** [comment]
Hi @lukechilds thanks for the question. My response to https://github.com/thisandagain/sentiment/issues/92 I think covers this. Please take a look and let me know if you have any further questions.

**Comment by twiss** [comment]
Some of these are explicitly given a value in AFINN-en-165.txt, but those values aren't used because sentiment doesn't support phrases (#35). For example, it already contains:

```
best damn		4
damn cute		3
damn good		4
fucking amazing		4
fucking beautiful	4
fucking cute		4
fucking fantastic	4
fucking good		4
fucking great		4
fucking hot		2
fucking love		4
fucking loves		4
fucking perfect		4
```
