### ISSUE TITLE
Could you explain what is the comparative value, and how it is computed

### ISSUE THREAD

**Issue by xhinker** [thisandagain/sentiment#119]
Could you explain what is the comparative value, and how it is computed

**Comment by thisandagain** [comment]
[This issue](https://github.com/thisandagain/sentiment/issues/107) includes a thread that covers how "comparative score" works and how to scale / offset it. 

TL;DR: Tokens are scored between -5 (highly negative) and 5 (highly positive) with 0 being "neutral". Comparative scores are simply SUM(tokens) / number of tokens. Details can be found in the AFINN whitepaper:
http://www2.imm.dtu.dk/pubdb/views/publication_details.php?id=6010

Sorry that the docs don't make this more clear!
