### ISSUE TITLE
Bundle for browser usage?

### ISSUE THREAD

**Issue by trainorpj** [thisandagain/sentiment#129]
Nice work on this library! I found it helpful for one of my pet-projects, but when I tried to use it in the browser I saw you don't have a bundled version.

Have you considered using something like [rollup](https://rollupjs.org/) to bundle you packages into a single deliverable?

**Comment by trainorpj** [comment]
I made a bundled version for my own use.  [You can check out my branch](https://github.com/trainorpj/sentiment/commit/3c4025841ec5062ce75b6c0702ee74d8094f8f42?diff=unified).

I made a few big changes, so I didn't want to submit a PR.  I'm happy to discuss this further.

**Comment by thisandagain** [comment]
Hi @trainorpj. I think most folks generally use webpack or browserify to bundle sentiment into a front-end project. I'd be happy to accept a PR that adds some dev dependency(s) to enable having a standalone bundle for this purpose though.

**Comment by trainorpj** [comment]
Sure thing! I'll clean up my branch when I get a chance.

**Comment by thisandagain** [comment]
On reflection I'd prefer that folks use something like webpack or browserify if they would like to include this in a client-side application. This helps keep the complexity of this repo down and is fairly normative with the rest of the NPM ecosystem.
