### ISSUE TITLE
Please document the max range of each value

### ISSUE THREAD

**Issue by benedictchen** [thisandagain/sentiment#137]
It is not totally clear regarding the resulting values what the max value could be. 

Please add to the documentation.

**Comment by trakout** [comment]
It used to be +/- 5 (score, not the comparative score), however it appears that this is changed as I have gotten 6 or even 7 as a value.

**Comment by pdw207** [comment]
Can this be closed or does this issue indicate an update to the README? @trakout were you able to reproduce the bug?

**Comment by trakout** [comment]
@pdw207
Sure, just re-tested and was able to reproduce. I have a demo here, some setup required for the Twitter Auth. https://github.com/trakout/simple-sentiment

If you edit [this line](https://github.com/trakout/simple-sentiment/blob/master/component/analysis.js#L95), you can observe sentiment scores greater than 5 or less than -5.


If you don't want to go through the setup process, I snagged some example copy from the output.
The following statement consistently outputs `score: -8, comparative: -0.17391304347826086`.

(the following words are from twitter and do not reflect my personal opinion or sentiment)
```
console.log(sentiment.analyze('So to recap-Trump wants kids held hostage. Sen. Schumer in no rush to end the kid hostage crisis. Paul Ryan in no rush to end the hostage crisis unless the Hastert rule is met. But Mitch McConnell is the only leader urging an immediate clean-bill fix.'))
```

**Comment by pdw207** [comment]
@thisandagain I can take this on. Sounds like a good first issue to pick up.

**Comment by pdw207** [comment]
As @thisandagain mentioned:
 > the score is the sum of all tokens, so that can have an arbitrary 

In the example you provided there are 4 negative tokens: `[ 'crisis', 'no', 'crisis', 'no' ]` and no positive tokens.   Each token has a value between -5 and 5. `crisis` has a AFINN score of -3 and `no` AFINN score of -1, so `-3 +  -1 +  -3 + -1 = -8`.

**Comment by pdw207** [comment]
I think this issue can be closed.

**Comment by ralyodio** [comment]
I'm also wondering why I always get around .02 to -.02 for comparitve score. Everything I run this on is "barely" positive or "barely" negative. I'm trying to create an indicator to reflect the negativity and positivity of an article but the marker is pretty much always in the middle making it rather useless.
