### ISSUE TITLE
Support overwriting emoji

### ISSUE THREAD

**Issue by ZM123** [thisandagain/sentiment#141]
Love this package, but is there a way to be able to overwrite the value of emoji in a similar way to overwriting word values? Thanks!

**Comment by elyas-bhy** [comment]
This feature is already supported, see [Adding and overwriting words](https://github.com/thisandagain/sentiment#adding-and-overwriting-words):

Example:
```js
const Sentiment = require('sentiment');
const sentiment = new Sentiment();
const result = sentiment.analyze('😦');
console.log(result); // -2
```

Override the weight of the emoji label:
```js
const Sentiment = require('sentiment');
const sentiment = new Sentiment();
const result = sentiment.analyze('😦', {
  extras: {
    '😦': -5
  }
});
console.log(result); // -5
```

**Comment by elyas-bhy** [comment]
Closing the issue. Feel free to re-open it if this doesn't meet your requirements.
