### ISSUE TITLE
Can this run in the browser?

### ISSUE THREAD

**Issue by angad19** [thisandagain/sentiment#151]
Can I install this on top of `create-react-app` and run it in the browser?

**Comment by austinaryain** [comment]
@angad19 This is definitely possible. I can create a repo to show you, or you can just test it out yourself. :)

`npm install --save sentiment`

`var Sentiment = require('sentiment');
var sentiment = new Sentiment();`

Works as you would expect it to. I have created a simple demo with it that displays sentiment score under an Input element as the user types.

**Comment by angad19** [comment]
Thank you! This is really helpful!
