### ISSUE TITLE
All the messages are getting logged

### ISSUE THREAD

**Issue by johnlongo** [thisandagain/sentiment#174]
All the messages are getting logged, how do I turn that off

**Comment by thisandagain** [comment]
@johnlongo Can you describe what you mean in more detail and/or provide a snippet of code that demonstrates your issue?

**Comment by johnlongo** [comment]
I have it deployed in node-red, when I look in the logs I'm seeing all the tweets getting logged (see below

10 Feb 19:22:19 - [info] [Twitter Stream:f5e1ae8c.fcb118] Xanik Xeus: @realDonaldTrump @nytimes @DanaPerino @FoxNews https://t.co/7MhSh6IINs
10 Feb 19:22:19 - [info] [Twitter Stream:f5e1ae8c.fcb118] skip: language https://twitter.com/statuses/1227025010314948609
10 Feb 19:22:19 - [info] [Twitter Stream:f5e1ae8c.fcb118] Gina Cook: Watch and share those of you with 10s of thousands of followers. It's really quite a beautiful tribute to our Count… https://t.co/RFCMjFLe43
10 Feb 19:22:19 - [info] [Twitter Stream:f5e1ae8c.fcb118] fedupwithtrump: @gtconway3d @realDonaldTrump Anyone that hurts 45’s feelings, or worse tells the truth he will destroy!  Those men,… https://t.co/FlMZt2be1T
10 Feb 19:22:19 - [info] [Twitter Stream:f5e1ae8c.fcb118] Deploribus Unum: RT @RepAndyBiggsAZ: There's so much that Republicans &amp; Democrats can work on together to improve the lives of everyday Americans.

**Comment by johnlongo** [comment]
My Mistake I had an Issue with another node
