### ISSUE TITLE
Can someone recommend any learning resources?

### ISSUE THREAD

**Issue by Aditya94A** [thisandagain/sentiment#176]
I'm looking to do sentiment analysis for news articles, simply looking for a positive/negative sentiment score to determine the 'tone' of the article.

How does this project's AFINN-165 wordlist approach compare to machine learning based approaches?

Can someone point to some learning resources? Would be a good idea to include this in readme as well.

**Comment by Aditya94A** [comment]
Hmmm.

This project tells me that `A man hit and killed by train` is better news than `an agri-tech startup raising debt funding`.

```
{
  score: -1,
  comparative: -0.1,
  calculation: [ { worth: 2 }, { killed: -3 } ],
  tokens: [
    'man',   'hit',
    'and',   'killed',
    'by',    'train',
    'in',    'lake',
    'worth', 'beach'
  ],
  words: [ 'worth', 'killed' ],
  positive: [ 'worth' ],
  negative: [ 'killed' ]
}
 Man hit and killed by train in Lake Worth Beach
```

```
{
  score: -2,
  comparative: -0.2222222222222222,
  calculation: [ { debt: -2 } ],
  tokens: [
    'agri-tech', 'startup',
    'clover',    'raises',
    'debt',      'funding',
    'from',      'alteria',
    'capital'
  ],
  words: [ 'debt' ],
  positive: [],
  negative: [ 'debt' ]
}
 Agri-tech startup Clover raises debt funding from Alteria Capital
```

😞

**Comment by thisandagain** [comment]
Hi @AdityaAnand1. I recommend that you review the following paper which talks about the most common ML-based approaches. This system is based on a valence word-list approach which is incredibly fast (good for doing large batches) and easy to port to other languages – but also limited in many ways (as you have discovered):

https://www.sciencedirect.com/science/article/pii/S0167923612001339
