### ISSUE TITLE
Vs Troll?

### ISSUE THREAD

**Issue by Philmod** [thisandagain/sentiment#18]
Hi,

Could you tell me what would be the differences with this other module you created? https://github.com/thisandagain/troll

Thanks,
Philmod

**Comment by BClark-Grad-Project** [comment]
The major difference is the use of the AFINN 111 standard.  It is a widely used standard for word weight in sentiment.

**Comment by thisandagain** [comment]
Troll and Sentiment both use AFINN as the underlying dataset. Troll adds a simple NN implementation on top of that which allows you to track the sentiment of a single user longitudinally over time (is this person being mean / rude consistently?).
