### ISSUE TITLE
Comparative

### ISSUE THREAD

**Issue by BClark-Grad-Project** [thisandagain/sentiment#20]
I have only reviewed sentiment analysis in respect to your comparative rate slightly but it seems a negative value like your `Cats are stupid.` example isn't right after referencing this article [Opinion Mining, Sentiment Analysis, and Opinion Spam Detection](http://www.cs.uic.edu/~liub/FBS/sentiment-analysis.html).  

Can you point me in the direction or explain how this metric applies.

**Comment by jacktuck** [comment]
Would be nice to have in the docs.

The comparative is score/total words

**Comment by thisandagain** [comment]
Yes, "comparative" is simply `score / tokens` as per:
https://github.com/thisandagain/sentiment/blob/develop/lib/index.js#L58
