### ISSUE TITLE
Missing something for "not"

### ISSUE THREAD

**Issue by itcropper** [thisandagain/sentiment#21]
"Not" can totally flip a string's meaning, but it and other similar adverbs are getting overlooked.

i.e., 

"I am not happy" 

scores a 3, when, because of the negative adverb in there preceding the adjective, it should get a score of -3.

**Comment by sahilsk** [comment]
same issue here:
"cracto is not good" it's scored 2 where  it should be -2.   :(

**Comment by thisandagain** [comment]
Tracking in #23
