### ISSUE TITLE
Spanish

### ISSUE THREAD

**Issue by svzosorio** [thisandagain/sentiment#50]
Hello, actually for support your sentiment algorithm my api translate spanish to english and response a phrase in english, but I need to support spanish lenguage, The process is add the spanish words in AFINN.txt or I need to add in other places?.

Thanks

**Comment by bobbybee** [comment]
(No soy @thisandagain pero creo que este tiene razón)

Sí, la idea principal es que todas las palabras ingleses son en AFINN.txt, con sus tantos sentimentales. Si construyera un archivo nuevo con las palabras españolas, pudiera usar este proyecto con frases españoles.

Es posible que hay que hacer una cosa o dos más, pero pienso que no. :smile:

¡Buena suerte!

**Comment by bobbybee** [comment]
Oh, también, cuando termine con AFINN.txt, hay que executar el archivo build/index.js para actualizar el proyecto.

**Comment by svzosorio** [comment]
@bobbybee Lo que hice para solucionarlo fue crear un archivo json e inyectarlo al proyecto como dicen las instrucciones para insertar nuevas palabras, y la traducción la hice con un script que me traducía cada palabra del JSON actual con bing, pero ya sabrás que el resultado no fue óptimo.

Acá el ejemplo de cómo lo hice y lo expuse en una api https://github.com/moreliahacks/api-sentimental-language/blob/master/dao/translate.js

**Comment by bobbybee** [comment]
@svzosorio :-)

**Comment by thisandagain** [comment]
Thanks for sharing your approach @svzosorio and thanks for your help @bobbybee !
