### ISSUE TITLE
Giving wrong result when using negative word in positive way

### ISSUE THREAD

**Issue by bansalvks** [thisandagain/sentiment#92]
Thanks for creating such a nice lib. but I regret to inform you that it is giving wrong results when a negative word is used in a positive manner.
```

var sentiment = require('sentiment');
 
var result = sentiment('I am dying to eat a kitkat!');
console.dir(result);   

///or

result = sentiment('your internet is not bad', knowladgeBase);
console.dir(result);
```

Please help

**Comment by Ghostbird** [comment]
Not a bug, the result you receive is a perfectly valid AFINN-165 score. Did you look at the paper that this tool is based on?
You expect the software to actually understand human sentiment, which is not what AFINN-165 does.

**Comment by bansalvks** [comment]
@Ghostbird Many thanks for replying. I understood what you said and I agree that you are completely right. Could you please guide me in the direction where I could find a solution for my problem, which is to guess the sentiment of the statement (+,-)

**Comment by Ghostbird** [comment]
I don't know about any other systems that can guess sentiment that are more accurate than AFINN. I think AFINN is generally good enough, but it depends on what you want.
Twitter uses AFINN for trend analysis for example. They know it's sometimes wrong, however even real humans will sometimes mistake the sentiment of a tweet. For Twitter it's more important that it can analyse a lot of tweets quickly, then that it's 100% accurate.
So if you're going to do a lot of analysis, and average the results, the occasional error is not important. If you need high accuracy for a single text, you'll need something else, but I'm not sure wether it exists already, or you'll have to do the research yourself.

**Comment by thisandagain** [comment]
Thanks for your help with this @Ghostbird 

--

@bansalvks If you are interested in Sentiment Analysis algorithms that properly account for part of speech (POS) I recommend you take a look at some of the foundational research on the subject. AFINN / this module are designed to be a high performance heuristic and does not account for negation and many other nuances of human language. Here are few to get you started:

Opinion Mining and Sentiment Analysis - http://dl.acm.org/citation.cfm?id=1454712
Sentiment analysis of Twitter Data - http://dl.acm.org/citation.cfm?id=2021114
